---
- name: Install development tools
  apt:
    name:
      - 'build-essential'
      - 'libssl-dev'
    state: present

- name: Install pip
  apt:
    name:
      - 'python-pip'
    state: present

- name: Install ntp
  apt:
    name:
      - 'ntp'
    state: present

- name: Install pyOpenSSL module
  pip:
    name: pyopenssl

- name: Install git
  apt:
    name: 'git'
    state: present

