---
- name: Restart ircd
  debug: msg="Determining if ircd-hybrid running first.."
  changed_when: True
  notify:
    - Check if ircd running
    - Stop ircd after check
    - Start ircd
    - Test connection to plaintext
    - Test connection to ssl

- name: Check if ircd running
  shell: ps aux | grep ircd
  changed_when: "'bin/ircd' in cmd.stdout"
  register: cmd

# bin/ircd -configfile etc/ircd.conf
- name: Stop ircd after check
  systemd:
    name: ircd-hybrid
    state: stopped

- name: Start ircd
  systemd:
    name: ircd-hybrid
    state: started

- name: Wait for plaintext port
  wait_for:
    port: "{{ plaintext_port }}"
    delay: 10
  when: plaintext_enabled

- name: Wait for ssl port
  wait_for:
    port: "{{ ssl_port }}"
    delay: 10
  when: ssl_enabled

- name: Test connection to plaintext
  irc:
     server: localhost
     port: "{{ plaintext_port }}"
     channel: "#does_not_exist"
     nick: "ansible_test"
     msg: "Testing.."
  when: plaintext_enabled

- name: Test connection to ssl
  irc:
     server: localhost
     port: "{{ ssl_port }}"
     channel: "#does_not_exist"
     nick: "ansible_test"
     msg: "Testing.."
  when: ssl_enabled
